### ISSUE TITLE
Some minor code flaws

### ISSUE THREAD

**Issue by abika** [vanitasvitae/smack-omemo-signal#3]
Hi! Here are some problems I had during testing:

* [x] The dependency with Bouncy Castle is bad for Android. The usual library used here is called Spongy Castle and the package path is different. But the code is only `Security.addProvider(new BouncyCastleProvider())`, better remove this and let the user do it.

* [x] `Exception in thread "Client Connector" java.lang.NoClassDefFoundError: org/jivesoftware/smackx/carbons/CarbonCopyReceivedListener`
-> smack-experimental required

* [x] -> user is null, connection must be authenticated
```
Exception in thread "main" java.lang.NullPointerException
	at org.jivesoftware.smackx.omemo.FileBasedOmemoStore.<init>(FileBasedOmemoStore.java:79)
	at org.jivesoftware.smackx.omemo.signal.SignalFileBasedOmemoStore.<init>(SignalFileBasedOmemoStore.java:54)
```

* [x] -> if the OmemoService is not set. There is a circular dependency here.
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.jivesoftware.smackx.omemo.OmemoManager.encrypt(OmemoManager.java:162)
```

---
Improvements:
 * [x] `checkAvailableAlgorithms();` why? throw exceptions when code is actually used
 * [x] and the ctor for OmemoService is executing a lot of tasks and network traffic. Better move that to some method(s).

---
Don't want to be picky. This is still great work! (And me bachelor thesis was more or less insignificant compared to this).

**Comment by vanitasvitae** [comment]
Hi! Thank you very much for your feedback. I'll tackle those points the next days :)

**Comment by vanitasvitae** [comment]
I removed the `Security.addProvider()` and updated the README.

I'll probably declare smack-experimental as a dependency later, not sure what is the best way for now.

`checkAvailableAlgorithms` is executed in order to fail immediately when required algorithms are not available. That way exception handling is a lot easier, because algorithm related exceptions can basically be ignored.

OmemoService now does no more networking stuff. I put that into `setup()`. Thanks for the hint, that was really bad design :)

I'm not sure, how to tackle the nullpointers when no omemoService is set. Probably the best way will be to throw IllegalStateExceptions in such a case?

Again thank you very much for your feedback and if you find more things that can be improved, please let me know :)

**Comment by abika** [comment]
> I'll probably declare smack-experimental as a dependency later, not sure what is the best way for now.

Adding it to the docs is enough imho.

> checkAvailableAlgorithms is executed in order to fail immediately when required algorithms are not available. That way exception handling is a lot easier, because algorithm related exceptions can basically be ignored.

I guess its ok IF it's guaranteed that no later exceptions are possible if the check passed first AND the check is crucial, i.e. OmemoService is unusable at all if it fails.

> I'm not sure, how to tackle the nullpointers when no omemoService is set. Probably the best way will be to throw IllegalStateExceptions in such a case?

Well, it raises the question why there are two classes. Circular dependencies are usually considered bad design. Does it make sense to use OmemoService without OmemoManager and vice versa? E.g. hiding one class inside the other is an option (but I haven't looked much into the code).

>Again thank you very much for your feedback and if you find more things that can be improved, please let me know :)

Sure, thanks for the improvements.

**Comment by vanitasvitae** [comment]
>I guess its ok IF it's guaranteed that no later exceptions are possible if the check passed first AND the check is crucial, i.e. OmemoService is unusable at all if it fails.

That's the case.

>Does it make sense to use OmemoService without OmemoManager and vice versa? E.g. hiding one class inside the other is an option (but I haven't looked much into the code).

The problem is, that smack-omemo is designed to work independently from implementations like smack-omemo-signal. Thats why the OmemoManager is the same object, regardless, which implementation is used. The OmemoService on the other hand encapsulates logic dependent on the used crypto library (eg. libsignal). Since smack-omemo-signal is licensed under GPL, smack-omemo CANNOT call or import any methods from there. Instead smack-omemo-signal has to "register" via the OmemoService implementation.
